<a href="https://colab.research.google.com/github/cristianomendieta/fraudes-bancarias-CIDAMO/blob/main/random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

# Modelo sem resampling de dados

In [15]:
#importa base train e base test
data_train = pd.read_csv('./data/dadosTrain.csv')
data_test = pd.read_csv('./data/dadosTest.csv')

FileNotFoundError: ignored

In [6]:
#visualizar cabecalho treino
data_train.head()

   Unnamed: 0  X        date  ... faixasjob  faixascity        distGeo
0           1  0  2019-01-01  ...         2         1.0   78773.820754
1           2  1  2019-01-01  ...         2         1.0   30216.618410
2           3  2  2019-01-01  ...         4         1.0  108102.911712
3           4  3  2019-01-01  ...         3         7.0   95685.115476
4           5  4  2019-01-01  ...         1         1.0   77702.395165

[5 rows x 30 columns]

In [7]:
#visualizar cabecalho teste
data_test.head()

   Unnamed: 0  Unnamed: 0.1  X  ... faixasjob faixascity        distGeo
0           0             1  0  ...       3.0        3.0   24613.746071
1           1             2  1  ...       2.0        3.0  104834.043428
2           2             3  2  ...       2.0        2.0   59204.795631
3           3             4  3  ...       3.0        1.0   27615.117073
4           4             5  4  ...       3.0        2.0  104423.174625

[5 rows x 31 columns]

In [8]:
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

In [13]:
#definicao variaveis
X_train = data_train[atributes]
y_train = data_train['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [ ]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

        Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         0
555581         0         0
555582         0         0
555583         0         0

[555584 rows x 2 columns]

In [ ]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.63      0.13      0.22      2010

    accuracy                           1.00    555584
   macro avg       0.81      0.57      0.61    555584
weighted avg       1.00      1.00      1.00    555584

Acuracia:
 0.9965819750028798

 Confusion Matrix :
 [[553417    157]
 [  1742    268]]

# Modelo com Undersample

In [ ]:
#importa base
data_undersample = pd.read_csv('./data/undersample_data.csv')

In [ ]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_undersample[atributes]
y_train = data_undersample['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [ ]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

        Gabarito  Previsao
0              0         0
1              0         0
2              0         0
3              0         0
4              0         0
...          ...       ...
555579         0         0
555580         0         0
555581         0         0
555582         0         0
555583         0         0

[555584 rows x 2 columns]

In [ ]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

Classification metrics:
               precision    recall  f1-score   support

           0       1.00      0.94      0.97    553574
           1       0.04      0.77      0.08      2010

    accuracy                           0.94    555584
   macro avg       0.52      0.86      0.53    555584
weighted avg       1.00      0.94      0.97    555584

Acuracia:
 0.9398524795530468

 Confusion Matrix :
 [[520616  32958]
 [   459   1551]]

# Modelo com Oversample

In [ ]:
#importa base
data_oversample = pd.read_csv('./data/oversample_data.csv')

In [ ]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_oversample[atributes]
y_train = data_oversample['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [ ]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

In [ ]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))

# Modelo com SMOTE

In [ ]:
#importa base
data_smote = pd.read_csv('./data/smote_data.csv')

In [ ]:
#atributos
atributes = ['cc_num', 'amt', 'gender', 'sec', 'faixascategory', 'faixasjob', 'faixascity', 'distGeo']

#definicao variaveis
X_train = data_smote[atributes]
y_train = data_smote['is_fraud']
X_test = data_test[atributes]
y_test = data_test['is_fraud']

#construcao do modelo
model = RandomForestClassifier()

#treinando o modelo
model = model.fit(X_train, y_train)
model

#dados de teste para o modelo
y_predict = model.predict(X_test)

In [ ]:
#comparando gabarito e previsoes da maquina
gabarito = pd.DataFrame({'Gabarito': y_test, 'Previsao': y_predict})
gabarito

In [ ]:
#metricas
print('Classification metrics: \n', metrics.classification_report(y_test,y_predict))
print('Acuracia: \n', accuracy_score(y_test, y_predict))
print('\n Confusion Matrix :\n', confusion_matrix(y_test, y_predict))